### ISSUE TITLE
Display power off

### ISSUE THREAD

**Issue by tpwrules** [jamwaffles/ssd1306#84]
Is it possible to power off the display using command 0xAE? This would enable saving power and OLED life in long-running applications.

**Comment by jamwaffles** [comment]
Certainly! Would you like to have a go at a PR? If not I'm happy to pick this up as I've got the hardware on hand to test.

**Comment by tpwrules** [comment]
Yeah, I'll give it a try. I do too but the library has been very useful for me so I'd like to be useful back.

**Comment by jamwaffles** [comment]
I think it would be better done as a new method because the programmer has the flexibility to call `.release()` separately or not. If the interface should be released, one can call `.display_off().release()` (or whatever method name you choose), otherwise just `.display_off()` and `.display_on()`. Does that make sense for your use case? I'm open to naming suggestions FWIW :slightly_smiling_face:.
